// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_methods
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_7AN0tie0G6HAgpz2t2GHI3JJiWEFBxw',
    appId: '1:571656092171:android:54fdc65bae024c43a1250e',
    messagingSenderId: '571656092171',
    projectId: 'waterbottle-c9b31',
    storageBucket: 'waterbottle-c9b31.firebasestorage.app',
    authDomain: 'waterbottle-c9b31.firebaseapp.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_7AN0tie0G6HAgpz2t2GHI3JJiWEFBxw',
    appId: '1:571656092171:android:54fdc65bae024c43a1250e',
    messagingSenderId: '571656092171',
    projectId: 'waterbottle-c9b31',
    storageBucket: 'waterbottle-c9b31.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_7AN0tie0G6HAgpz2t2GHI3JJiWEFBxw',
    appId: '1:571656092171:android:54fdc65bae024c43a1250e',
    messagingSenderId: '571656092171',
    projectId: 'waterbottle-c9b31',
    storageBucket: 'waterbottle-c9b31.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_7AN0tie0G6HAgpz2t2GHI3JJiWEFBxw',
    appId: '1:571656092171:android:54fdc65bae024c43a1250e',
    messagingSenderId: '571656092171',
    projectId: 'waterbottle-c9b31',
    storageBucket: 'waterbottle-c9b31.firebasestorage.app',
    authDomain: 'waterbottle-c9b31.firebaseapp.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_7AN0tie0G6HAgpz2t2GHI3JJiWEFBxw',
    appId: '1:571656092171:android:54fdc65bae024c43a1250e',
    messagingSenderId: '571656092171',
    projectId: 'waterbottle-c9b31',
    storageBucket: 'waterbottle-c9b31.firebasestorage.app',
  );
}
